bug:
  - head-branch: ['^fix', '^bugfix', 'fix']

ci/cd:
  - changed-files:
      - any-glob-to-any-file:
          - '.github/**/*'

dependencies:
  - changed-files:
      - any-glob-to-any-file:
          - 'package*.json'
          - 'pnpm*.json'

documentation:
  - changed-files:
      - any-glob-to-any-file:
          - '*.md'

javascript:
  - changed-files:
      - any-glob-to-any-file:
          - '**/*.js'

github_actions:
  - changed-files:
      - any-glob-to-any-file:
          - '.github/workflows/*'

feature:
  - head-branch: ['^feat', 'feature']

typescript:
  - changed-files:
      - any-glob-to-any-file:
          - '**/*.ts'
