pull_request_rules:
  - name: automatic merge for Dependabot pull requests
    conditions:
      - author=dependabot[bot]
      - check-success=Application CI
      - check-success=Pull-Request Checks
    actions:
      merge:
        method: merge
