spring:
  datasource:
    url: 'jdbc:h2:mem:eldoria;DB_CLOSE_DELAY=-1'
  h2:
    console:
      enabled: 'true'
      path: '/h2-console'
  jpa:
    hibernate:
      ddl-auto: 'create-drop'
logging:
  level:
    io.github.bbortt.eldoria: DEBUG
