export const INIT_PHASE = 'INIT_PHASE';

export const ROLL_PLACEMENT_PHASE = 'ROLL_PLACEMENT_PHASE';
export const GATHER_GROUP_PHASE = 'GATHER_GROUP_PHASE';

export const ROLL_TURN_ORDER_PHASE = 'ROLL_TURN_ORDER_PHASE';
export const MOVEMENT_PHASE = 'MOVEMENT_PHASE';
export const ACTION_PHASE = 'ACTION_PHASE';
export const TURN_END_PHASE = 'TURN_END_PHASE';
