name: Application CI

on:
  push:
    branches-ignore:
      - main

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  ci:
    name: 'Build and Test'
    runs-on: ubuntu-latest
    if: github.event_name != 'pull_request'
    steps:
      - name: Checkout
        uses: actions/checkout@v5
      - name: Check if PR exists
        uses: 8BitJonny/gh-get-current-pr@4.0.0
        id: check
      - name: Install pnpm
        if: '!steps.check.outputs.number'
        uses: pnpm/action-setup@v4
        with:
          run_install: false
      - name: Cache turbo build setup
        if: '!steps.check.outputs.number'
        uses: actions/cache@v4
        with:
          path: .turbo
          key: ${{ runner.os }}-turbo-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-turbo-
      - name: Install Node.js
        if: '!steps.check.outputs.number'
        uses: actions/setup-node@v5
        with:
          node-version: 23
          cache: 'pnpm'
      - name: Install Dependencies
        if: '!steps.check.outputs.number'
        run: pnpm install --frozen-lockfile
      - name: Run Unit-Tests
        if: '!steps.check.outputs.number'
        run: pnpm run test -- --coverage
