name: Application CI

on:
  push:
    branches-ignore:
      - main

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

env:
  DISPLAY: ":99"
  XVFB_PARMS: "-screen 0 1920x1080x24 -nolisten unix"

jobs:
  ci:
    name: 'Eldoria: Build and Test'
    runs-on: ubuntu-latest
    if: github.event_name != 'pull_request'
    env:
      SPRING_OUTPUT_ANSI_ENABLED: DETECT
      SPRING_JPA_SHOW_SQL: false
    steps:
      - name: Check if PR exists
        id: check
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          prs=$(gh pr list \
            --repo "$GITHUB_REPOSITORY" \
            --head '${{ github.head_ref }}' \
            --base '${{ github.base_ref }}' \
            --json title \
            --jq 'length')
          if ((prs > 0)); then
            echo "Found open PR!"
            echo "skip=true" >> "$GITHUB_OUTPUT"
          fi
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 21
      - uses: actions/cache@v4
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar
          restore-keys: ${{ runner.os }}-sonar
      - uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle
      - name: Set up Virtual Display (for Linux)
        if: runner.os == 'Linux'
        run: |
          Xvfb ${{env.DISPLAY}} ${{env.XVFB_PARMS}} &
      - name: Run Tests
        if: '!steps.check.outputs.skip'
        run: ./gradlew checkstyleNohttp check --no-daemon -Dlogging.level.ROOT=OFF
      - name: SonarQube Analysis
        if: '!steps.check.outputs.skip'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: ./gradlew sonar --no-daemon -Dsonar.organization=bbortt-github -Dsonar.host.url=https://sonarcloud.io
