name: Release Pipeline

on:
  push:
    branches:
      - main

jobs:
  release-please:
    runs-on: ubuntu-latest
    environment: build
    permissions:
      contents: write
      pull-requests: write
    steps:
      - uses: googleapis/release-please-action@v4
        with:
          token: ${{ secrets.RELEASE_TOKEN }}
          release-type: node
