name: Pull-Request Checks

on:
  pull_request:
    branches:
      - main

concurrency:
  group: mr-${{ github.ref }}
  cancel-in-progress: true

jobs:
  labeler:
    name: 'Pull-Request Labels'
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
      - uses: actions/labeler@v6
  lint:
    name: 'Lint'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5
      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          run_install: false
      - name: Cache turbo build setup
        uses: actions/cache@v4
        with:
          path: .turbo
          key: ${{ runner.os }}-turbo-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-turbo-
      - name: Install Node.js
        uses: actions/setup-node@v6
        with:
          node-version: 23
          cache: 'pnpm'
      - name: Install Dependencies
        run: pnpm install --frozen-lockfile
      - name: Check Formatting
        run: pnpm run prettier:check
      - name: Lint Changes
        run: pnpm run lint
  ci:
    name: 'Build and Test'
    runs-on: ubuntu-latest
    permissions:
      checks: write
      pull-requests: write
    steps:
      - name: Checkout
        uses: actions/checkout@v5
        with:
          fetch-depth: 0
      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          run_install: false
      - name: Cache turbo build setup
        uses: actions/cache@v4
        with:
          path: .turbo
          key: ${{ runner.os }}-turbo-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-turbo-
      - name: Install Node.js
        uses: actions/setup-node@v6
        with:
          node-version: 23
          cache: 'pnpm'
      - name: Install Dependencies
        run: pnpm install --frozen-lockfile
      - name: Run Unit-Tests
        run: pnpm run test -- --coverage
      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      - name: Build Static Sites
        run: pnpm run build
      - name: Upload Website Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: website
          path: apps/web/out
      - name: Publish Test Results
        uses: EnricoMi/publish-unit-test-result-action@v2
        if: always()
        with:
          files: |
            **/reports/*.xml
