name: Pull-Request Checks

on:
  pull_request:
    branches:
      - main

concurrency:
  group: mr-${{ github.ref }}
  cancel-in-progress: true

env:
  DISPLAY: ":99"
  XVFB_PARMS: "-screen 0 1920x1080x24 -nolisten unix"

jobs:
  gradle:
    name: 'Gradle Wrapper Validation'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: gradle/wrapper-validation-action@v3
  lint:
    name: 'Eldoria: Lint'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 22.2.0
      - uses: actions/cache@v4
        with:
          path: .npm
          key: ${{ runner.os }}-npm
          restore-keys: ${{ runner.os }}-npm
      - run: npm ci --cache .npm
      - name: Validate code format
        run: npm run prettier:check
      - name: Validate commit messages
        if: github.event_name == 'pull_request'
        run: npx --no-install commitlint --from ${{ github.event.pull_request.base.sha }} --to ${{ github.event.pull_request.head.sha }} --verbose
  ci:
    name: 'Eldoria: Build and Test'
    runs-on: ubuntu-latest
    env:
      SPRING_OUTPUT_ANSI_ENABLED: DETECT
      SPRING_JPA_SHOW_SQL: false
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 21
      - uses: actions/cache@v4
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar
          restore-keys: ${{ runner.os }}-sonar
      - uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle
      - name: Set up Virtual Display (for Linux)
        if: runner.os == 'Linux'
        run: |
          Xvfb ${{env.DISPLAY}} ${{env.XVFB_PARMS}} &
      - name: Run Tests
        run: ./gradlew checkstyleNohttp check --no-daemon -Dlogging.level.ROOT=OFF
      - name: SonarQube Analysis
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: ./gradlew sonar --no-daemon -Dsonar.organization=bbortt-github -Dsonar.host.url=https://sonarcloud.io
