name: Publish

on:
  push:
    tags:
      - 'v*'

jobs:
  publish:
    name: Publish to GitHub Pages
    runs-on: ubuntu-latest
    environment: build
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          run_install: false
      - name: Cache turbo build setup
        uses: actions/cache@v4
        with:
          path: .turbo
          key: ${{ runner.os }}-turbo-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-turbo-
      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'pnpm'
      - name: Install Dependencies
        run: pnpm install
      - name: Prepare Build
        run: |
          echo 'ELDORIA_ASSET_PATH="https://github.com/bbortt/eldoria"' > apps/web/.env
          echo 'ELDORIA_BASE_PATH="/eldoria"' >> apps/web/.env
      - name: Build Pages
        run: pnpm run build
      - name: Publish to GH Pages
        run: |
          git remote set-url origin https://git:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git
          npx --no-install gh-pages -u "GitHub Actions Bot <actions@github.com>" -b gh-pages -d apps/web/out -t true
        env:
          GITHUB_TOKEN: ${{ secrets.RELEASE_TOKEN }}
