name: Publish

on:
  push:
    tags:
      - 'v*'

jobs:
  publish:
    name: Publish to GitHub Pages
    runs-on: ubuntu-latest
    environment: build
    steps:
      - name: Checkout
        uses: actions/checkout@v5
      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          run_install: false
      - name: Cache turbo build setup
        uses: actions/cache@v4
        with:
          path: .turbo
          key: ${{ runner.os }}-turbo-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-turbo-
      - name: Install Node.js
        uses: actions/setup-node@v5
        with:
          node-version: 23
          cache: 'pnpm'
      - name: Install Dependencies
        run: pnpm install --frozen-lockfile
      - name: Prepare Build
        run: |
          echo 'NEXT_PUBLIC_ELDORIA_BASE_PATH="/eldoria"' > apps/web/.env
      - name: Build Pages
        run: pnpm run build
      - name: Publish to GH Pages
        run: |
          git remote set-url origin https://git:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git
          npx --no-install gh-pages -u "GitHub Actions Bot <actions@github.com>" -b gh-pages -d apps/web/out -t true
        env:
          GITHUB_TOKEN: ${{ secrets.RELEASE_TOKEN }}
