name: Release Preparation

on:
  push:
    branches:
      - 'release-please-*'

jobs:
  publish:
    name: Fix Release Preparation
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}
      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          run_install: false
      - name: Cache turbo build setup
        uses: actions/cache@v4
        with:
          path: .turbo
          key: ${{ runner.os }}-turbo-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-turbo-
      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'pnpm'
      - name: Install Dependencies
        run: pnpm install
      - name: Fix package.json
        run: pnpm run prettier:format
      - name: Commit
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: 'ci(release): fix package.json formatting'
          file_pattern: 'package.json'
